### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by juniorknot** [Snoopke/telegram_for_sport_bets#2]
Hello good morning, I have a question for you, are you creating the referral link from the system https://1xpartners.com/partner directly through the api.php? Could you upload the complete code please? Can you give me your telegram or WhatsApp?

**Comment by Snoopke** [comment]
Hello! As I remember, this is complete code.  You have to change only line 32 in api.js with your own link from account on xbet.  Put bots and api.js+api.php in directory C:\bots for example. Start server "php -s 127.0.0.1:84 -t C:\bots"  and then start any bot script.
